name: Deploy Backend to EC2

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | sed 's/./& /g' | head -5

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            whoami
            cd ~/Jobsforce/backend
            git pull origin main
            pm2 restart all
