name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"  # Trigger only when changes occur in the backend folder

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json  # Cache npm dependencies

    - name: Verify Backend Directory and Files
      run: ls -la backend  # Debugging: Check if package-lock.json exists

    - name: Install Dependencies
      run: |
        if [ -f "backend/package-lock.json" ]; then
          npm ci
        else
          npm install
        fi
      working-directory: backend

    - name: Set Up Environment Variables
      run: |
        touch .env
        echo "${{ secrets.PROD_ENV_FILE }}" > .env
      working-directory: backend

  
